Repository Amaroq7/SPMod, pull requests merged in 2018-07, with the labels that each got.

#22 Basic operations on float numbers
  scripts/include/float.inc
  scripts/include/spmod.inc
  src/FloatNatives.cpp
  src/SPGlobal.cpp
  src/meson.build
  src/spmod.hpp
Labels: enhancement

#26 Fixed hook table initializing
  src/meta_api.cpp
Labels: bug

#27 Newline at PrintToServer end; CamelCase
  scripts/include/natives.inc
  scripts/include/spmod.inc
  scripts/script.sp
  src/CoreNatives.cpp
  src/meson.build
Labels: enhancement

#25 Generating conf file by meson
  meson.build
  src/SPConfig.hpp.in
  src/spmod.hpp
Labels: enhancement

#29 Added GetGameTime native
  scripts/include/spmod.inc
  src/CoreNatives.cpp
Labels: enhancement

#31 Fix crash
  src/RehldsApi.cpp
  src/dllapi.cpp
  src/meta_api.cpp
  src/spmod.hpp
Labels: bug

#23 Timer manager
  include/public/ISPGlobal.hpp
  include/public/ITimerSystem.hpp
  scripts/include/spmod.inc
  scripts/include/timers.inc
  src/SPGlobal.cpp
  src/SPGlobal.hpp
  src/TimerNatives.cpp
  src/TimerSystem.cpp
  src/TimerSystem.hpp
  src/dllapi.cpp
  src/meson.build
  src/meta_api.cpp
  src/spmod.hpp
Labels: enhancement

#17 Cvar manager
  include/public/ICvarSystem.hpp
  include/public/ISPGlobal.hpp
  scripts/include/cvars.inc
  src/CvarSystem.cpp
  src/CvarSystem.hpp
  src/CvarsNatives.cpp
  src/ForwardSystem.cpp
  src/ForwardSystem.hpp
  src/RehldsApi.cpp
  src/SPGlobal.cpp
  src/SPGlobal.hpp
  src/dllapi.cpp
  src/meson.build
  src/meta_api.cpp
  src/spmod.hpp
Labels: enhancement

#34 Docgen fixes
  scripts/include/forwards.inc
  scripts/include/messages.inc
Labels: documentation

#33 Set up deployment
  .travis.yml
  appveyor.yml
  meson.build
  meson_options.txt
  patches/gcc-nodbg-clang.patch
  travis/build.sh
  travis/package.sh
  travis/prepare.sh
Labels: enhancement, meson

#35 Utils & refactor
  include/public/IForwardSystem.hpp
  include/public/ISPGlobal.hpp
  include/public/IUtilsSystem.hpp
  scripts/include/forwards.inc
  scripts/include/string.inc
  src/CmdNatives.cpp
  src/CmdSystem.cpp
  src/CmdSystem.hpp
  src/CoreNatives.cpp
  src/CvarSystem.cpp
  src/CvarSystem.hpp
  src/CvarsNatives.cpp
  src/ForwardSystem.cpp
  src/ForwardSystem.hpp
  src/ForwardsNatives.cpp
  src/LoggingSystem.cpp
  src/LoggingSystem.hpp
  src/NativeSystem.cpp
  src/NativeSystem.hpp
  src/PluginSystem.cpp
  src/PluginSystem.hpp
  src/PrintfImpl.cpp
  src/SPGlobal.cpp
  src/SPGlobal.hpp
  src/SrvCommand.cpp
  src/StringNatives.cpp
  src/TimerSystem.cpp
  src/TimerSystem.hpp
  src/UtilsSystem.cpp
  src/UtilsSystem.hpp
  src/meson.build
  src/spmod.hpp
Labels: enhancement
