Repository Amaroq7/SPMod, pull requests merged in 2018-06, with the labels that each got.

#3 initial messages support
  README.md
  scripts/include/messages.inc
  scripts/include/spmod.inc
  src/MessageNatives.cpp
  src/SPGlobal.cpp
  src/meson.build
  src/spmod.hpp
Labels: enhancement

#20 Update messages doc
  scripts/include/messages.inc
Labels: documentation

#16 Cmd manager
  include/public/IForwardSystem.hpp
  scripts/include/commands.inc
  scripts/include/spmod.inc
  src/CmdNatives.cpp
  src/CmdSystem.cpp
  src/CmdSystem.hpp
  src/ForwardSystem.cpp
  src/ForwardSystem.hpp
  src/SPGlobal.cpp
  src/SPGlobal.hpp
  src/SrvCommand.cpp
  src/dllapi.cpp
  src/meson.build
  src/meta_api.cpp
  src/spmod.hpp
Labels: documentation, enhancement, needs-review, needs-testing
