Repository Amaroq7/SPMod, pull requests merged in 2019-10, with the labels that each got.

#54 Add info about plugin
  subprojects/sourcepawn/PluginSystem.cpp
Labels: enhancement

#53 Project folders
  appveyor/package.ps1
  scripting/include/clients.inc
  scripting/include/commands.inc
  scripting/include/cvars.inc
  scripting/include/float.inc
  scripting/include/forwards.inc
  scripting/include/menus.inc
  scripting/include/messages.inc
  scripting/include/natives.inc
  scripting/include/spmod.inc
  scripting/include/string.inc
  scripting/include/timers.inc
  scripting/script.sp
  travis/package.sh
Labels: enhancement

#58 Unify files header
  include/public/ICmdSystem.hpp
  include/public/ICvarSystem.hpp
  include/public/IForwardSystem.hpp
  include/public/IHelpers.hpp
  include/public/IInterface.hpp
  include/public/ILoggerSystem.hpp
  include/public/IMenuSystem.hpp
  include/public/INativeProxy.hpp
  include/public/IPlayerSystem.hpp
  include/public/IPluginSystem.hpp
  include/public/ISPGlobal.hpp
  include/public/ITimerSystem.hpp
  include/public/IUtilsSystem.hpp
  src/CmdSystem.cpp
  src/CmdSystem.hpp
  src/CvarSystem.cpp
  src/CvarSystem.hpp
  src/ExtensionSystem.cpp
  src/ExtensionSystem.hpp
  src/ForwardSystem.cpp
  src/ForwardSystem.hpp
  src/LoggingSystem.cpp
  src/LoggingSystem.hpp
  src/MenuSystem.cpp
  src/MenuSystem.hpp
  src/NativeProxy.cpp
  src/NativeProxy.hpp
  src/PlayerSystem.cpp
  src/PlayerSystem.hpp
  src/RehldsApi.cpp
  src/SPConfig.hpp.in
  src/SPGlobal.cpp
  src/SPGlobal.hpp
  src/SrvCommand.cpp
  src/TimerSystem.cpp
  src/TimerSystem.hpp
  src/UtilsSystem.cpp
  src/UtilsSystem.hpp
  src/dllapi.cpp
  src/engine_api.cpp
  src/h_export.cpp
  src/meta_api.cpp
  src/spmod.hpp
  subprojects/example/DummyPluginMngr.cpp
  subprojects/example/DummyPluginMngr.hpp
  subprojects/example/ext.cpp
  subprojects/example/ext.hpp
Labels: under-review

#55 Fix windows build
  src/spmod.hpp
Labels: windows

#56 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
Labels: needs-review

#57 Add engine funcs to api
  include/public/ICmdSystem.hpp
  include/public/IEngineFuncs.hpp
  include/public/ISPGlobal.hpp
  src/EngineFuncs.cpp
  src/EngineFuncs.hpp
  src/SPGlobal.cpp
  src/SPGlobal.hpp
  src/meson.build
  src/spmod.hpp
Labels: enhancement
